// This file was generated by Prisma.
// Ensure DATABASE_URL is available for Prisma CLI commands (Windows shells may not inherit env vars).
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Load DATABASE_URL from common places in a monorepo.
// `dotenv/config` loads from process.cwd() by default; for safety we try a few paths.
import { config as dotenvConfig } from "dotenv";

// best-effort: no-throw loading
dotenvConfig({ path: "./.env" });
dotenvConfig({ path: "../.env" });
dotenvConfig({ path: "../../.env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
